import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../components/nav-bar/nav-bar";
import Dashboardbg from "../components/dashboard-bg/dashboard-bg";
import Sidebar from "../components/side-bar/side-bar";

import "./globals.css";
import SidebarWrapper from "../components/wrraper-layout/wrraper-layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
              <SidebarWrapper>
          {children}
        </SidebarWrapper>
      
      </body>
    </html>
  );
}
